[project]
name = "udacity-generative-ai-course-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "chromadb>=0.3.23",
    "dotenv>=0.9.9",
    "pandas>=2.3.0",
    "pydantic>=2.12.5",
    "pydantic-core>=2.41.5",
    "pytest>=9.0.2",
    "ragas>=0.4.2",
    "streamlit==1.47.0",
]
